import Link from 'next/link'

const Hero = () => {
  return (
    <section className='text-gray-600 body-font'>
      <div className='container mx-auto flex px-5 py-24 md:flex-row flex-col items-center'>
        <div className='lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center'>
          <h1 className='title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900'>
            Finding Stunning Images
            <br className='hidden lg:inline-block' />
            Made Easy
          </h1>
          <p className='mb-8 leading-relaxed'>
            Discover a vast collection of high-quality images for your projects
            with our AI-powered image search tool powered by the Unsplash API.
            Say goodbye to hours of searching and let our intelligent algorithms
            find the perfect images for you.
          </p>
          <div className='flex justify-center'>
            <Link href='find-image'>
              <button className='inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg'>
                Find image
              </button>
            </Link>
            <Link href='generate-image'>
              <button className='ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg'>
                Generate image by AI
              </button>
            </Link>
          </div>
        </div>
        <div className='lg:max-w-lg lg:w-full md:w-1/2 w-5/6'>
          <img
            className='object-cover object-center rounded'
            alt='hero picture'
            title='This image generated by AI too'
            src='https://dummyimage.com/720x600'
          />
        </div>
      </div>
    </section>
  )
}
export default Hero
